// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: codes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cube.Codes {

  /// <summary>Holder for reflection information generated from codes.proto</summary>
  public static partial class CodesReflection {

    #region Descriptor
    /// <summary>File descriptor for codes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CodesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtjb2Rlcy5wcm90bxIFY29kZXMqoAEKCUNsb3NlQ29kZRIOCgpET19OT1Rf",
            "VVNFEAASEAoLT05fV0FJVExJU1QQ+CMSEwoOSU5DT01QTEVURV9LWUMQ+SMS",
            "EwoOVU5BUFBST1ZFRF9LWUMQ+iMSEAoLQkFEX01FU1NBR0UQ3CQSEQoMTk9f",
            "SEVBUlRCRUFUEN0kEhAKC1VOU1BFQ0lGSUVEEIcnIgUIARCfHyIJCIgnEP//",
            "//8HQhJaA2dvL6oCCkN1YmUuQ29kZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cube.Codes.CloseCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Custom error codes. Sent on a best-effort basis on the WebSocket
  /// `CloseFrame`.
  /// </summary>
  public enum CloseCode {
    [pbr::OriginalName("DO_NOT_USE")] DoNotUse = 0,
    [pbr::OriginalName("ON_WAITLIST")] OnWaitlist = 4600,
    [pbr::OriginalName("INCOMPLETE_KYC")] IncompleteKyc = 4601,
    [pbr::OriginalName("UNAPPROVED_KYC")] UnapprovedKyc = 4602,
    [pbr::OriginalName("BAD_MESSAGE")] BadMessage = 4700,
    [pbr::OriginalName("NO_HEARTBEAT")] NoHeartbeat = 4701,
    [pbr::OriginalName("UNSPECIFIED")] Unspecified = 4999,
  }

  #endregion

}

#endregion Designer generated code
