// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: codes.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Custom error codes. Sent on a best-effort basis on the WebSocket
// `CloseFrame`.
type CloseCode int32

const (
	CloseCode_DO_NOT_USE     CloseCode = 0
	CloseCode_ON_WAITLIST    CloseCode = 4600
	CloseCode_INCOMPLETE_KYC CloseCode = 4601
	CloseCode_UNAPPROVED_KYC CloseCode = 4602
	CloseCode_BAD_MESSAGE    CloseCode = 4700
	CloseCode_NO_HEARTBEAT   CloseCode = 4701
	CloseCode_UNSPECIFIED    CloseCode = 4999
)

// Enum value maps for CloseCode.
var (
	CloseCode_name = map[int32]string{
		0:    "DO_NOT_USE",
		4600: "ON_WAITLIST",
		4601: "INCOMPLETE_KYC",
		4602: "UNAPPROVED_KYC",
		4700: "BAD_MESSAGE",
		4701: "NO_HEARTBEAT",
		4999: "UNSPECIFIED",
	}
	CloseCode_value = map[string]int32{
		"DO_NOT_USE":     0,
		"ON_WAITLIST":    4600,
		"INCOMPLETE_KYC": 4601,
		"UNAPPROVED_KYC": 4602,
		"BAD_MESSAGE":    4700,
		"NO_HEARTBEAT":   4701,
		"UNSPECIFIED":    4999,
	}
)

func (x CloseCode) Enum() *CloseCode {
	p := new(CloseCode)
	*p = x
	return p
}

func (x CloseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_codes_proto_enumTypes[0].Descriptor()
}

func (CloseCode) Type() protoreflect.EnumType {
	return &file_codes_proto_enumTypes[0]
}

func (x CloseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseCode.Descriptor instead.
func (CloseCode) EnumDescriptor() ([]byte, []int) {
	return file_codes_proto_rawDescGZIP(), []int{0}
}

var File_codes_proto protoreflect.FileDescriptor

var file_codes_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x2a, 0xa0, 0x01, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0b, 0x4f, 0x4e, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x4c, 0x49, 0x53,
	0x54, 0x10, 0xf8, 0x23, 0x12, 0x13, 0x0a, 0x0e, 0x49, 0x4e, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x5f, 0x4b, 0x59, 0x43, 0x10, 0xf9, 0x23, 0x12, 0x13, 0x0a, 0x0e, 0x55, 0x4e, 0x41,
	0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x5f, 0x4b, 0x59, 0x43, 0x10, 0xfa, 0x23, 0x12, 0x10,
	0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0xdc, 0x24,
	0x12, 0x11, 0x0a, 0x0c, 0x4e, 0x4f, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54,
	0x10, 0xdd, 0x24, 0x12, 0x10, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x87, 0x27, 0x22, 0x05, 0x08, 0x01, 0x10, 0x9f, 0x1f, 0x22, 0x09, 0x08, 0x88,
	0x27, 0x10, 0xff, 0xff, 0xff, 0xff, 0x07, 0x42, 0x12, 0x5a, 0x03, 0x67, 0x6f, 0x2f, 0xaa, 0x02,
	0x0a, 0x43, 0x75, 0x62, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_codes_proto_rawDescOnce sync.Once
	file_codes_proto_rawDescData = file_codes_proto_rawDesc
)

func file_codes_proto_rawDescGZIP() []byte {
	file_codes_proto_rawDescOnce.Do(func() {
		file_codes_proto_rawDescData = protoimpl.X.CompressGZIP(file_codes_proto_rawDescData)
	})
	return file_codes_proto_rawDescData
}

var file_codes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_codes_proto_goTypes = []interface{}{
	(CloseCode)(0), // 0: codes.CloseCode
}
var file_codes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codes_proto_init() }
func file_codes_proto_init() {
	if File_codes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_codes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codes_proto_goTypes,
		DependencyIndexes: file_codes_proto_depIdxs,
		EnumInfos:         file_codes_proto_enumTypes,
	}.Build()
	File_codes_proto = out.File
	file_codes_proto_rawDesc = nil
	file_codes_proto_goTypes = nil
	file_codes_proto_depIdxs = nil
}
