// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: codes.proto

package codes;

public final class Codes {
  private Codes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Custom error codes. Sent on a best-effort basis on the WebSocket
   * `CloseFrame`.
   * </pre>
   *
   * Protobuf enum {@code codes.CloseCode}
   */
  public enum CloseCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DO_NOT_USE = 0;</code>
     */
    DO_NOT_USE(0),
    /**
     * <code>ON_WAITLIST = 4600;</code>
     */
    ON_WAITLIST(4600),
    /**
     * <code>INCOMPLETE_KYC = 4601;</code>
     */
    INCOMPLETE_KYC(4601),
    /**
     * <code>UNAPPROVED_KYC = 4602;</code>
     */
    UNAPPROVED_KYC(4602),
    /**
     * <code>BAD_MESSAGE = 4700;</code>
     */
    BAD_MESSAGE(4700),
    /**
     * <code>NO_HEARTBEAT = 4701;</code>
     */
    NO_HEARTBEAT(4701),
    /**
     * <code>UNSPECIFIED = 4999;</code>
     */
    UNSPECIFIED(4999),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DO_NOT_USE = 0;</code>
     */
    public static final int DO_NOT_USE_VALUE = 0;
    /**
     * <code>ON_WAITLIST = 4600;</code>
     */
    public static final int ON_WAITLIST_VALUE = 4600;
    /**
     * <code>INCOMPLETE_KYC = 4601;</code>
     */
    public static final int INCOMPLETE_KYC_VALUE = 4601;
    /**
     * <code>UNAPPROVED_KYC = 4602;</code>
     */
    public static final int UNAPPROVED_KYC_VALUE = 4602;
    /**
     * <code>BAD_MESSAGE = 4700;</code>
     */
    public static final int BAD_MESSAGE_VALUE = 4700;
    /**
     * <code>NO_HEARTBEAT = 4701;</code>
     */
    public static final int NO_HEARTBEAT_VALUE = 4701;
    /**
     * <code>UNSPECIFIED = 4999;</code>
     */
    public static final int UNSPECIFIED_VALUE = 4999;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CloseCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CloseCode forNumber(int value) {
      switch (value) {
        case 0: return DO_NOT_USE;
        case 4600: return ON_WAITLIST;
        case 4601: return INCOMPLETE_KYC;
        case 4602: return UNAPPROVED_KYC;
        case 4700: return BAD_MESSAGE;
        case 4701: return NO_HEARTBEAT;
        case 4999: return UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CloseCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CloseCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CloseCode>() {
            public CloseCode findValueByNumber(int number) {
              return CloseCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return codes.Codes.getDescriptor().getEnumTypes().get(0);
    }

    private static final CloseCode[] VALUES = values();

    public static CloseCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CloseCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:codes.CloseCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013codes.proto\022\005codes*\240\001\n\tCloseCode\022\016\n\nDO" +
      "_NOT_USE\020\000\022\020\n\013ON_WAITLIST\020\370#\022\023\n\016INCOMPLE" +
      "TE_KYC\020\371#\022\023\n\016UNAPPROVED_KYC\020\372#\022\020\n\013BAD_ME" +
      "SSAGE\020\334$\022\021\n\014NO_HEARTBEAT\020\335$\022\020\n\013UNSPECIFI" +
      "ED\020\207\'\"\005\010\001\020\237\037\"\t\010\210\'\020\377\377\377\377\007B\022Z\003go/\252\002\nCube.Co" +
      "desb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
