/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.15.8
 * source: codes.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace codes {
    export enum CloseCode {
        DO_NOT_USE = 0,
        ON_WAITLIST = 4600,
        INCOMPLETE_KYC = 4601,
        UNAPPROVED_KYC = 4602,
        BAD_MESSAGE = 4700,
        NO_HEARTBEAT = 4701,
        UNSPECIFIED = 4999
    }
}
